# Generated by Django 5.2.8 on 2025-11-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRecruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
