# Generated by Django 5.2.8 on 2025-11-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRecruitment', '0003_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.TextField(default='No Resume Provided'),
        ),
    ]
