# Generated by Django 5.2.8 on 2025-12-03 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobRecruitment', '0006_candidate_user_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobRecruitment.company'),
        ),
    ]
